<?php

namespace Database\Seeders;

use App\Models\HotelInfo;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class HotelInfoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        HotelInfo::updateOrCreate([
            'city'=>'Makkah',
            'type'=>'5 Star Premium',
            'name'=>'Raffles Palace',
            'code'=>'5PRaffles',
            'distance'=>'0',
            'double_price'=>'980.00',
            'triple'=>'1140.00',
            'quad'=>'0.00',
            'offerd'=>'Elaf',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
         

        HotelInfo::updateOrCreate([
            'city'=>'Makkah',
            'type'=>'5 Star Premium',
            'name'=>'Dar Al Tawhid',
            'code'=>'5PTawhid',
            'distance'=>'0',
            'double_price'=>'1040.00',
            'triple'=>'1310.00',
            'quad'=>'0.00',
            'offerd'=>'Hotel',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);

        HotelInfo::updateOrCreate([
            'city'=>'Makkah',
            'type'=>'5 Star Premium',
            'name'=>'Fairmont',
            'code'=>'5PFairmont',
            'distance'=>'0',
            'double_price'=>'660.00',
            'triple'=>'770.00',
            'quad'=>'880.00',
            'offerd'=>'Elaf',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        
        HotelInfo::updateOrCreate([
            'city'=>'Makkah',
            'type'=>'5 Star Premium',
            'name'=>'Makkah Hotel',
            'code'=>'5PHotel',
            'distance'=>'0',
            'double_price'=>'690.00',
            'triple'=>'880.00',
            'quad'=>'910.00',
            'offerd'=>'HOtel',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        
        HotelInfo::updateOrCreate([
            'city'=>'Makkah',
            'type'=>'5 Star Premium',
            'name'=>'Conrad Makkah',
            'code'=>'5PConrad',
            'distance'=>'50',
            'double_price'=>'550.00',
            'triple'=>'660.00',
            'quad'=>'770.00',
            'offerd'=>'Dar Al Eiman',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        
        HotelInfo::updateOrCreate([
            'city'=>'Makkah',
            'type'=>'5 Star Premium',
            'name'=>'Hayat Regancey',
            'code'=>'5PRegancey',
            'distance'=>'50',
            'double_price'=>'600.00',
            'triple'=>'700.00',
            'quad'=>'800.00',
            'offerd'=>'haramain',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Makkah',
            'type'=>'5 Star Gold',
            'name'=>'Swissotel',
            'code'=>'5GSwissotel',
            'distance'=>'0',
            'double_price'=>'450.00',
            'triple'=>'550.00',
            'quad'=>'650.00',
            'offerd'=>'Dar Al Eiman',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Makkah',
            'type'=>'5 Star Gold',
            'name'=>'Pullman ZamZam',
            'code'=>'5GZamZam',
            'distance'=>'0',
            'double_price'=>'490.00',
            'triple'=>'590.00',
            'quad'=>'690.00',
            'offerd'=>'Hotel',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Makkah',
            'type'=>'5 Star Gold',
            'name'=>'Movenpick',
            'code'=>'5GMovenpick',
            'distance'=>'0',
            'double_price'=>'570.00',
            'triple'=>'670.00',
            'quad'=>'770.00',
            'offerd'=>'Elaf',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Makkah',
            'type'=>'5 Star Gold',
            'name'=>'Makkah Tower',
            'code'=>'5GTower',
            'distance'=>'0',
            'double_price'=>'655.00',
            'triple'=>'710.00',
            'quad'=>'950.00',
            'offerd'=>'Hotel',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Makkah',
            'type'=>'5 Star Gold',
            'name'=>'Hilton Suites',
            'code'=>'5GHiltonSuites',
            'distance'=>'60',
            'double_price'=>'640.00',
            'triple'=>'750.00',
            'quad'=>'860.00',
            'offerd'=>'Elaf',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Makkah',
            'type'=>'5 Star Gold',
            'name'=>'Elaf Kinda',
            'code'=>'5GElafKinda',
            'distance'=>'50',
            'double_price'=>'470.00',
            'triple'=>'550.00',
            'quad'=>'630.00',
            'offerd'=>'Elaf',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Makkah',
            'type'=>'5 Star Sliver',
            'name'=>'Sheraton Makkah',
            'code'=>'5SSheraton',
            'distance'=>'100',
            'double_price'=>'330.00',
            'triple'=>'390.00',
            'quad'=>'450.00',
            'offerd'=>'Hotel',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Makkah',
            'type'=>'5 Star Sliver',
            'name'=>'Shaza Makkah',
            'code'=>'5SShaza',
            'distance'=>'100',
            'double_price'=>'410.00',
            'triple'=>'465.00',
            'quad'=>'520.00',
            'offerd'=>'Elaf',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Makkah',
            'type'=>'5 Star Sliver',
            'name'=>'Hilton Convention',
            'code'=>'5SHilton',
            'distance'=>'150',
            'double_price'=>'465.00',
            'triple'=>'520.00',
            'quad'=>'575.00',
            'offerd'=>'Ealf',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Makkah',
            'type'=>'5 Star Sliver',
            'name'=>'Marriott Makkah',
            'code'=>'5SMarriott',
            'distance'=>'250',
            'double_price'=>'485.00',
            'triple'=>'550.00',
            'quad'=>'650.00',
            'offerd'=>'Elaf',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Makkah',
            'type'=>'3 Star',
            'name'=>'Firdous Al Umrah',
            'code'=>'5SFirdous',
            'distance'=>'600',
            'double_price'=>'210.00',
            'triple'=>'230.00',
            'quad'=>'260.00',
            'offerd'=>'Diamond',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Makkah',
            'type'=>'3 Star',
            'name'=>'Tharawat Al Andalyssya',
            'code'=>'3SAndalyssya',
            'distance'=>'450',
            'double_price'=>'280.00',
            'triple'=>'290.00',
            'quad'=>'300.00',
            'offerd'=>'Diamond',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Makkah',
            'type'=>'3 Star',
            'name'=>'Dar Al Eiman Grand',
            'code'=>'3SGrand',
            'distance'=>'700',
            'double_price'=>'200.00',
            'triple'=>'210.00',
            'quad'=>'220.00',
            'offerd'=>'Dar Al Eiman',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Makkah',
            'type'=>'3 Star',
            'name'=>'Matheer Al Jiwar',
            'code'=>'3SMatheer',
            'distance'=>'600',
            'double_price'=>'230.00',
            'triple'=>'240.00',
            'quad'=>'250.00',
            'offerd'=>'Diamond',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Makkah',
            'type'=>'3 Star',
            'name'=>'Dar Al Eiman Khalil',
            'code'=>'3SKhalil',
            'distance'=>'600',
            'double_price'=>'150.00',
            'triple'=>'160.00',
            'quad'=>'170.00',
            'offerd'=>'Dar Al Eiman',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Makkah',
            'type'=>'3 Star',
            'name'=>'Marsa Al Jariah',
            'code'=>'3SMarsa',
            'distance'=>'300',
            'double_price'=>'270.00',
            'triple'=>'290.00',
            'quad'=>'350.00',
            'offerd'=>'Diamond',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Makkah',
            'type'=>'3 Star Standard',
            'name'=>'Areej Al Falah',
            'code'=>'3STAreej',
            'distance'=>'250',
            'double_price'=>'270.00',
            'triple'=>'290.00',
            'quad'=>'350.00',
            'offerd'=>'Diamond',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Makkah',
            'type'=>'3 Star Standard',
            'name'=>'Burj Al Sultan',
            'code'=>'3STBurj',
            'distance'=>'200',
            'double_price'=>'270.00',
            'triple'=>'320.00',
            'quad'=>'370.00',
            'offerd'=>'Diamond',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Makkah',
            'type'=>'3 Star Standard',
            'name'=>'Riyadah Al Hijra',
            'code'=>'3STHijra',
            'distance'=>'550',
            'double_price'=>'240.00',
            'triple'=>'245.00',
            'quad'=>'250.00',
            'offerd'=>'Diamond',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Makkah',
            'type'=>'3 Star Standard',
            'name'=>'Ghala Al Taj',
            'code'=>'3STGhala',
            'distance'=>'550',
            'double_price'=>'270.00',
            'triple'=>'280.00',
            'quad'=>'290.00',
            'offerd'=>'Diamond',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Makkah',
            'type'=>'3 Star Standard',
            'name'=>'Nosour Al Mohajreen',
            'code'=>'3STMohajreen',
            'distance'=>'500',
            'double_price'=>'270.00',
            'triple'=>'275.00',
            'quad'=>'280.00',
            'offerd'=>'Diamond',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Makkah',
            'type'=>'Economy',
            'name'=>'Rehab al Bustan',
            'code'=>'ECBustan',
            'distance'=>'600',
            'double_price'=>'120.00',
            'triple'=>'120.00',
            'quad'=>'120.00',
            'offerd'=>'zamzam',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Makkah',
            'type'=>'Economy',
            'name'=>'Areej al Zahabi',
            'code'=>'ECZahabi',
            'distance'=>'600',
            'double_price'=>'120.00',
            'triple'=>'120.00',
            'quad'=>'120.00',
            'offerd'=>'zamzam',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Makkah',
            'type'=>'Economy',
            'name'=>'Hotel Loulouh',
            'code'=>'ECLoulouh',
            'distance'=>'600',
            'double_price'=>'130.00',
            'triple'=>'130.00',
            'quad'=>'130.00',
            'offerd'=>'zamzam',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Makkah',
            'type'=>'Economy',
            'name'=>'Jowharat al Hijra',
            'code'=>'ECJowharat',
            'distance'=>'700',
            'double_price'=>'130.00',
            'triple'=>'130.00',
            'quad'=>'130.00',
            'offerd'=>'zamzam',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'5 Star Premium',
            'name'=>'Oberoi Madinah',
            'code'=>'5POberoi',
            'distance'=>'0',
            'double_price'=>'1950.00',
            'triple'=>'2500.00',
            'quad'=>'0.00',
            'offerd'=>'Dar Al Eiman',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'5 Star Premium',
            'name'=>'Dar Al Taqwa',
            'code'=>'5PTaqwa',
            'distance'=>'0',
            'double_price'=>'705.00',
            'triple'=>'980.00',
            'quad'=>'0.00',
            'offerd'=>'Dar Al Eiman',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'5 Star Premium',
            'name'=>'Anwar Al Madinah Movenpick',
            'code'=>'5PMovenpick',
            'distance'=>'0',
            'double_price'=>'600.00',
            'triple'=>'720.00',
            'quad'=>'840.00',
            'offerd'=>'Hotel',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'5 Star Premium',
            'name'=>'Madinah Hilton',
            'code'=>'5PHilton',
            'distance'=>'50',
            'double_price'=>'800.00',
            'triple'=>'1020.00',
            'quad'=>'0.00',
            'offerd'=>'Elaf',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'5 Star Premium',
            'name'=>'Dar Al Iman Intercontinental',
            'code'=>'5PContinental',
            'distance'=>'50',
            'double_price'=>'955.00',
            'triple'=>'1130.00',
            'quad'=>'0.00',
            'offerd'=>'Elaf',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'5 Star Gold',
            'name'=>'Grand Mercury',
            'code'=>'5GMercury',
            'distance'=>'100',
            'double_price'=>'700.00',
            'triple'=>'800.00',
            'quad'=>'900.00',
            'offerd'=>'Haramin',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'5 Star Gold',
            'name'=>'Millennium Al ',
            'code'=>'5GAqeeq',
            'distance'=>'150',
            'double_price'=>'600.00',
            'triple'=>'700.00',
            'quad'=>'800.00',
            'offerd'=>'Haramin',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'5 Star Gold',
            'name'=>'Al Haram Hotel',
            'code'=>'5GHaram',
            'distance'=>'100',
            'double_price'=>'600.00',
            'triple'=>'700.00',
            'quad'=>'800.00',
            'offerd'=>'Haramin',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'5 Star Gold',
            'name'=>'Rove Al Madinah',
            'code'=>'5GRove',
            'distance'=>'180',
            'double_price'=>'710.00',
            'triple'=>'790.00',
            'quad'=>'980.00',
            'offerd'=>'Haramin',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'5 Star Gold',
            'name'=>'Nokhba Royal Inn',
            'code'=>'5GNokhba',
            'distance'=>'200',
            'double_price'=>'830.00',
            'triple'=>'875.00',
            'quad'=>'1070.00',
            'offerd'=>'Haramin',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'5 Star Gold',
            'name'=>'Coral Al Madinah',
            'code'=>'5GCoral',
            'distance'=>'50',
            'double_price'=>'520.00',
            'triple'=>'630.00',
            'quad'=>'740.00',
            'offerd'=>'Elaf',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'5 Star Gold',
            'name'=>'Shaza Al Madinah',
            'code'=>'5GShaza',
            'distance'=>'50',
            'double_price'=>'640.00',
            'triple'=>'750.00',
            'quad'=>'860.00',
            'offerd'=>'Elaf',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'5 Star Silver',
            'name'=>'Al Eiman Royal',
            'code'=>'5SRoyal',
            'distance'=>'200',
            'double_price'=>'440.00',
            'triple'=>'505.00',
            'quad'=>'575.00',
            'offerd'=>'Dar Al Eiman',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'5 Star Silver',
            'name'=>'Crowne Plaza',
            'code'=>'5SCrowne',
            'distance'=>'200',
            'double_price'=>'400.00',
            'triple'=>'450.00',
            'quad'=>'500.00',
            'offerd'=>'Dar Al Eiman',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'5 Star Silver',
            'name'=>'Dar Al Hijra Intercontinental',
            'code'=>'5SHijra',
            'distance'=>'300',
            'double_price'=>'400.00',
            'triple'=>'500.00',
            'quad'=>'600.00',
            'offerd'=>'Hotel',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'5 Star Silver',
            'name'=>'Pullman ZamZam',
            'code'=>'5SZamZam',
            'distance'=>'100',
            'double_price'=>'400.00',
            'triple'=>'450.00',
            'quad'=>'510.00',
            'offerd'=>'Elaf',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'3 Star',
            'name'=>'Frontel Al Harithya',
            'code'=>'3SHarithya',
            'distance'=>'100',
            'double_price'=>'540.00',
            'triple'=>'640.00',
            'quad'=>'740.00',
            'offerd'=>'Elaf',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'3 Star',
            'name'=>'Elaf Taibah',
            'code'=>'3SElafTaibah',
            'distance'=>'90',
            'double_price'=>'450.00',
            'triple'=>'525.00',
            'quad'=>'600.00',
            'offerd'=>'Elaf',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'3 Star',
            'name'=>'Dar AL Eiman Al Manar',
            'code'=>'3SManar',
            'distance'=>'200',
            'double_price'=>'305.00',
            'triple'=>'310.00',
            'quad'=>'315.00',
            'offerd'=>'Dar Al Eiman',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'3 Star',
            'name'=>'Al Eiman Taibah',
            'code'=>'3STaibah',
            'distance'=>'300',
            'double_price'=>'275.00',
            'triple'=>'280.00',
            'quad'=>'285.00',
            'offerd'=>'Dal Al Eiman',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'3 Star',
            'name'=>'Elaf Grand Al Majeedi',
            'code'=>'3SMajeedi',
            'distance'=>'50',
            'double_price'=>'520.00',
            'triple'=>'620.00',
            'quad'=>'720.00',
            'offerd'=>'Elaf',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'3 Star',
            'name'=>'Al Salhiya Diamond',
            'code'=>'3SSalhiya',
            'distance'=>'50',
            'double_price'=>'305.00',
            'triple'=>'310.00',
            'quad'=>'315.00',
            'offerd'=>'Dar Al Eiman',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'3 Star',
            'name'=>'Dar Al Eiman Al Quibla',
            'code'=>'3SQuibla',
            'distance'=>'100',
            'double_price'=>'240.00',
            'triple'=>'245.00',
            'quad'=>'250.00',
            'offerd'=>'Dar Al Eiman',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'3 Star',
            'name'=>'Al Eiman Ohud',
            'code'=>'3SOhud',
            'distance'=>'400',
            'double_price'=>'185.00',
            'triple'=>'190.00',
            'quad'=>'195.00',
            'offerd'=>'Dar Al Eiman',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'3 Star Silver',
            'name'=>'Al Eiman Al Nour',
            'code'=>'3SNour',
            'distance'=>'300',
            'double_price'=>'185.00',
            'triple'=>'190.00',
            'quad'=>'195.00',
            'offerd'=>'Dar Al Eiman',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'3 Star Standard',
            'name'=>'Karam Golden',
            'code'=>'3STGolden',
            'distance'=>'400',
            'double_price'=>'160.00',
            'triple'=>'170.00',
            'quad'=>'180.00',
            'offerd'=>'zamzam',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'3 Star Standard',
            'name'=>'Karam Silver',
            'code'=>'3STSilver',
            'distance'=>'400',
            'double_price'=>'160.00',
            'triple'=>'170.00',
            'quad'=>'180.00',
            'offerd'=>'zamzam',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'3 Star Standard',
            'name'=>'Makarem Al Mahbouba',
            'code'=>'3STMahbouba',
            'distance'=>'100',
            'double_price'=>'185.00',
            'triple'=>'190.00',
            'quad'=>'195.00',
            'offerd'=>'Dar Al Eiman',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'3 Star Standard',
            'name'=>'Rehab al Sharq',
            'code'=>'3STSharq',
            'distance'=>'650',
            'double_price'=>'150.00',
            'triple'=>'160.00',
            'quad'=>'180.00',
            'offerd'=>'zamzam',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'Economy',
            'name'=>'Lugen al Khair',
            'code'=>'ECLugen',
            'distance'=>'400',
            'double_price'=>'140.00',
            'triple'=>'150.00',
            'quad'=>'160.00',
            'offerd'=>'zamzam',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'Economy',
            'name'=>'Huda Al Masi',
            'code'=>'ECMasi',
            'distance'=>'600',
            'double_price'=>'120.00',
            'triple'=>'120.00',
            'quad'=>'120.00',
            'offerd'=>'zamzam',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'Economy',
            'name'=>'Mehrab Palace',
            'code'=>'ECMehrab',
            'distance'=>'600',
            'double_price'=>'120.00',
            'triple'=>'120.00',
            'quad'=>'120.00',
            'offerd'=>'zamzam',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
        HotelInfo::updateOrCreate([
            'city'=>'Madinah',
            'type'=>'Economy',
            'name'=>'Diyar al Ghara',
            'code'=>'ECGhara',
            'distance'=>'400',
            'double_price'=>'120.00',
            'triple'=>'130.00',
            'quad'=>'140.00',
            'offerd'=>'zamzam',
            'valid'=>'14 Dec',
            'notes'=>'BB',
            'googleMap'=>'',
        ]);
    }
}
